### ISSUE TITLE
Update to new NHL API url.

### ISSUE THREAD

**Issue by r5mao** [jordanmao/NHL-ranker-for-Tims-Challenge#1]
https://github.com/jordanmao/tims-hockey-challenge-autopicker/blob/aa31a9d2867f6ab1c2114eadef54900e290148b8/autopicker/player.py#L154C32-L154C32

Known issue: https://gitlab.com/dword4/nhlapi/-/issues/110
https://www.reddit.com/r/nhl/comments/17qtnn0/nhl_api_down/

New API domain: `https://api-web.nhle.com/v1/`
https://gitlab.com/dword4/nhlapi/-/blob/master/new-api.md#new-api-documentation

**Comment by jordanmao** [comment]
Fixed: 7b6d90f1c365c60f6c3518bba0999808ef524caf
